#!/bin/bash
# Startup script for the Git2Prov service
### BEGIN INIT INFO
# Provides:             git2prov
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Git2Prov Service
# Description:          Git2Prov Service
### END INIT INFO
PID_FILE=/var/run/git2prov.pid
LOG_FILE=/var/log/git2prov.log
APPLICATION_DIR=/home/node/git2prov/

start() {
  if [ -f $PID_FILE ]
  then
    echo "$PID_FILE exists, process is already running or crashed"
  else
    echo "Starting server..."
    cd $APPLICATION_DIR
    sudo node proxy.js 80
    sudo -u node node index.js 8905 2>&1 >> $LOG_FILE
    echo $! > $PID_FILE;
  fi
}
stop() {
  if [ ! -f $PID_FILE ]
  then
    echo "$PID_FILE does not exist, process is not running"
  else
    echo "Stopping server..."
    echo "Killing `cat $PID_FILE`"
    kill `cat $PID_FILE`;
    rm $PID_FILE;
    echo "Server stopped"
  fi
}

restart() {
  if [ ! -f $PID_FILE ]
  then
    echo "$PID_FILE does not exist, process is not running"

  else
    echo "Restarting server..."
    echo "Killing `cat $PID_FILE`"
    kill `cat $PID_FILE`;
    rm $PID_FILE;
    cd $APPLICATION_DIR
    sudo node proxy.js 80
    sudo -u node node index.js 8905 2>&1 >> $LOG_FILE
    echo $! > $PID_FILE;
    echo "Server restarted"
  fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac